version: '3.5'

services:
  app:
    build: .
    command: ["./scripts/wait-for-it.sh", "${REDIS_URL}", "--", "./scripts/run.sh"]
    environment:
      - HERALD_URI=${HERALD_URI}
      - REDIS_URL=${REDIS_URL}
      - REDIS_EXPIRATION=${REDIS_EXPIRATION}
    volumes:
      - .:/go/src/github.com/cfx-cv/nami:z
    expose:
      - "80"
    depends_on:
      - db
    networks:
      default:
      gofeed:
        aliases:
          - nami_app

  db:
    image: redis:4.0
    volumes:
      - redis_volume:/data

volumes:
  redis_volume:

networks:
  gofeed:
    external: true
